### ISSUE TITLE
Add AsyncSeek support

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [sfackler/tokio-io-timeout#10]
I was integrating this crate for a project that I use, but I need the Timeout wrapper to also provide the `AsyncSeek` trait, just as the underlying handle does. I can't directly use the `get_ref` or `get_mut` because the Timeout wrapper itself is inside another wrapper (for buffered r/w).

I have added a `AsyncSeek` impl for both the `TimeoutReader` and `TimeoutWriter`, the implementation just passes the seek calls to the underling handle without checking time. Can I send a PR for it?

**Comment by sfackler** [comment]
Seems reasonable to me!
